
gtnh.settings.blowdryerTag = 0.2.2
modName = Psi
modId = psi
modGroup = vazkii.psi
useModGroupForPublishing = true
autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = xXseesXx
enableModernJavaSyntax = jabel
enableGenericInjection = true
generateGradleTokenClass = vazkii.psi.common.lib.LibMisc
gradleTokenVersion = VERSION
replaceGradleTokenInFile =
apiPackage =
accessTransformersFile =
usesMixins = false
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage =
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false
usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
includeWellKnownRepositories = true
excludeWellKnownRepositories =
usesMavenPublishing = true
modrinthProjectId =
modrinthRelations =
curseForgeProjectId =
curseForgeRelations =
org.gradle.configuration-cache = true
org.gradle.parallel = true
